import pyautogui as auto
from time import sleep
sleep(10)
t = 0
v = 0
while True:
  auto.hotkey("ctrl", "enter")
  sleep(1)
  auto.click(x=731, y=17)
  sleep(1)
  auto.click(x=383, y=113)
  sleep(1)
  auto.click(x=383, y=113)
  sleep(1)
  auto.write("pp")
  sleep(1)
  auto.press("enter")
  sleep(1)
  auto.click(x=1650, y=828)
  sleep(1)
  auto.click(x=2039, y=1067)
  sleep(1)
  auto.hotkey("alt", "tab")
  sleep(1)
  input("Stiskni enter pro pokračování")
  sleep(1)
  auto.hotkey("alt", "tab")
  sleep(1)
  auto.click(x=1419, y=381)
  sleep(1)
  auto.hotkey("ctrl", "w")
  sleep(1)
  auto.click(x=237, y=31)
  sleep(1)
  auto.press("tab")
  sleep(1)
  auto.press("tab")
  sleep(1)
  auto.press("tab")
  sleep(1)
  v = v + 1
  sleep(1)
  print(v)